### ISSUE TITLE
Bug: cursor in search bar is not aligned properly.

### ISSUE THREAD

**Issue by priyanshumaitra** [priyanshumaitra/instagram-home-feed-clone#35]

**Comment by sayan404** [comment]
want to work .. assign me @priyanshumaitra

**Comment by priyanshumaitra** [comment]
> want to work .. assign me @priyanshumaitra

@sayan404 Thanks for your interest in contributing to this repo. But, this issue is already linked with a PR that has been made earlier https://github.com/priyanshumaitra/instagram-home-feed-clone/pull/34. You can check other issues or raise a new issue.

**Comment by lata-11** [comment]
Sir, (@priyanshumaitra ) I have fixed that issue and raised a PR. Kindly merge my PR under Hacktoberfest.

**Comment by lata-11** [comment]
Sir (@priyanshumaitra ) Please merge my PR.
