### ISSUE TITLE
Make the nav items mobile responsive

### ISSUE THREAD

**Issue by priyanshumaitra** [priyanshumaitra/instagram-home-feed-clone#6]
Nav items i.e. 

- Home
- Message
- New post
- Explore
- Activity
- Profile

Make sure they move to the bottom whenever the site is opened on any mobile environment.

**Comment by jsvigneshkanna** [comment]
Please assign this to my name, will raise pr

**Comment by priyanshumaitra** [comment]
> Please assign this to my name, will raise pr

Sure! Assigning you.

**Comment by priyanshumaitra** [comment]
@jsvigneshkanna The UI is messed up. The output is not as expected :point_down: 

![screencapture-priyanshumaitra-github-io-instagram-home-feed-clone-2022-10-10-22_45_25](https://user-images.githubusercontent.com/26964412/194921132-444f5b9b-8027-44ea-9bca-9abf05f5cbbc.png)
