### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by priyanshumaitra** [priyanshumaitra/instagram-home-feed-clone#7]
Write a **README** that helps beginners and others to contribute to this project.
From setting up the environment, installing Git and everything that they need to contribute.

**Effected file:** `README.md`

**Comment by priyanshumaitra** [comment]
@Rashmisingh-18 The motive is to make the `README` more understandable for beginners to contribute to this project.
You may add the necessary steps to begin with Git & GitHub to cloning and contributing to this project etc.
Take reference from [here](https://github.com/su1nta/Originals)

**Comment by poojasharma097** [comment]
Hello, I would like to update the README.md file. Please assign this issue to me. @priyanshumaitra

**Comment by priyanshumaitra** [comment]
@poojasharma097 Sure, assigning you. Go ahead!
