### ISSUE TITLE
Add hover arrow to slide through stories

### ISSUE THREAD

**Issue by priyanshumaitra** [priyanshumaitra/instagram-home-feed-clone#9]
Add an arrow to view the stories like below :point_down: 

![hover-arrow](https://user-images.githubusercontent.com/26964412/194863567-38240b67-6ba6-4ee9-b4f0-c75806ab7af3.jpeg)

**Comment by rrsingh11** [comment]
Hey @priyanshumaitra Can I work on this issue ?

**Comment by priyanshumaitra** [comment]
@rrsingh11 Okay, assigning you!

**Comment by rrsingh11** [comment]
Hey, @priyanshumaitra this is a video for reference.

https://user-images.githubusercontent.com/86000208/194938664-d2e29a7d-0016-4c01-a95f-e0caad9e904a.mp4

Please merge #14  if this is what you wanted,
Hope my contribution was helpful.

Have a good day ahead!

**Comment by priyanshumaitra** [comment]
@rrsingh11 Thanks for the contribution, and sorry for the delay. I was quite busy yesterday to check.
